# Generated by Django 6.0.3 on 2026-03-10 12:58

import account.models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Adresse e‑mail de l'utilisateur",
                        max_length=254,
                        unique=True,
                        verbose_name="Adresse e‑mail",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        help_text="Prénom de l'utilisateur",
                        max_length=30,
                        verbose_name="Prénom",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        help_text="Nom de famille de l'utilisateur",
                        max_length=30,
                        verbose_name="Nom",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("", "Unset"), ("H", "Homme"), ("F", "Femme")],
                        default="",
                        help_text="Sexe de l'utilisateur",
                        max_length=1,
                        verbose_name="Sexe",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        default=None,
                        help_text="Image de profil de l'utilisateur",
                        null=True,
                        upload_to=account.models.get_avatar_path,
                        verbose_name="Photo de profil",
                    ),
                ),
                (
                    "avatar_cropped",
                    models.ImageField(
                        blank=True,
                        default=None,
                        help_text="Version recadrée de la photo de profil",
                        max_length=1000,
                        null=True,
                        upload_to=account.models.get_avatar_path,
                        verbose_name="Photo de profil recadrée",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indique si l'utilisateur peut se connecter au panneau d'administration.",
                        verbose_name="Statut personnel",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indique si ce compte doit être considéré comme actif.",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Horodatage de l'inscription de l'utilisateur.",
                        verbose_name="Date d'inscription",
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Horodatage de la dernière modification du profil.",
                        verbose_name="Date de modification",
                    ),
                ),
                (
                    "password_reset_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Code de réinitialisation du mot de passe (généré automatiquement).",
                        null=True,
                        verbose_name="Mot de passe - Code de réinitialisation",
                    ),
                ),
                (
                    "password_reset_code_created_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Date à laquelle le code de réinitialisation a été créé.",
                        null=True,
                        verbose_name="Mot de passe - Date de création du code",
                    ),
                ),
                (
                    "task_id_password_reset",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="Identifiant de la tâche Celery de réinitialisation du mot de passe.",
                        max_length=40,
                        null=True,
                        verbose_name="Mot de passe - Task ID de réinitialisation",
                    ),
                ),
                (
                    "default_password_set",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indique si le mot de passe par défaut a été défini.",
                        verbose_name="Mot de passe par défaut défini",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
                "ordering": ("-date_joined",),
            },
        ),
        migrations.CreateModel(
            name="HistoricalCustomUser",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Adresse e‑mail de l'utilisateur",
                        max_length=254,
                        verbose_name="Adresse e‑mail",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        help_text="Prénom de l'utilisateur",
                        max_length=30,
                        verbose_name="Prénom",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        help_text="Nom de famille de l'utilisateur",
                        max_length=30,
                        verbose_name="Nom",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("", "Unset"), ("H", "Homme"), ("F", "Femme")],
                        default="",
                        help_text="Sexe de l'utilisateur",
                        max_length=1,
                        verbose_name="Sexe",
                    ),
                ),
                (
                    "avatar",
                    models.TextField(
                        blank=True,
                        default=None,
                        help_text="Image de profil de l'utilisateur",
                        max_length=100,
                        null=True,
                        verbose_name="Photo de profil",
                    ),
                ),
                (
                    "avatar_cropped",
                    models.TextField(
                        blank=True,
                        default=None,
                        help_text="Version recadrée de la photo de profil",
                        max_length=1000,
                        null=True,
                        verbose_name="Photo de profil recadrée",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indique si l'utilisateur peut se connecter au panneau d'administration.",
                        verbose_name="Statut personnel",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Indique si ce compte doit être considéré comme actif.",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Horodatage de l'inscription de l'utilisateur.",
                        verbose_name="Date d'inscription",
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        help_text="Horodatage de la dernière modification du profil.",
                        verbose_name="Date de modification",
                    ),
                ),
                (
                    "password_reset_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Code de réinitialisation du mot de passe (généré automatiquement).",
                        null=True,
                        verbose_name="Mot de passe - Code de réinitialisation",
                    ),
                ),
                (
                    "password_reset_code_created_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Date à laquelle le code de réinitialisation a été créé.",
                        null=True,
                        verbose_name="Mot de passe - Date de création du code",
                    ),
                ),
                (
                    "task_id_password_reset",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="Identifiant de la tâche Celery de réinitialisation du mot de passe.",
                        max_length=40,
                        null=True,
                        verbose_name="Mot de passe - Task ID de réinitialisation",
                    ),
                ),
                (
                    "default_password_set",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indique si le mot de passe par défaut a été défini.",
                        verbose_name="Mot de passe par défaut défini",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique Utilisateur",
                "verbose_name_plural": "Historiques Utilisateurs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
