[pytest]
DJANGO_SETTINGS_MODULE = reservation_backend.settings_test
# -- recommended but optional:
python_files = tests.py test_*.py *_tests.py
filterwarnings = ignore:'asyncio.*':DeprecationWarning
# Coverage options
addopts = --cov=reservation_backend --cov-branch --cov-report=term --cov-report=xml:coverage.xml --cov-config=.coveragerc
