# Generated by Django 6.0.3 on 2026-04-07 16:53

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0001_initial"),
        ("reservation", "0012_remove_notification_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="HistoricalNotification",
                    fields=[
                        (
                            "id",
                            models.BigIntegerField(
                                auto_created=True,
                                blank=True,
                                db_index=True,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "title",
                            models.CharField(max_length=255, verbose_name="Titre"),
                        ),
                        ("message", models.TextField(verbose_name="Message")),
                        (
                            "notification_type",
                            models.CharField(
                                choices=[
                                    ("check_in", "Arrivée"),
                                    ("check_out", "Départ"),
                                ],
                                max_length=20,
                                verbose_name="Type",
                            ),
                        ),
                        (
                            "is_read",
                            models.BooleanField(default=False, verbose_name="Lu"),
                        ),
                        (
                            "date_created",
                            models.DateTimeField(
                                blank=True,
                                db_index=True,
                                editable=False,
                                verbose_name="Date création",
                            ),
                        ),
                        (
                            "history_id",
                            models.AutoField(primary_key=True, serialize=False),
                        ),
                        ("history_date", models.DateTimeField(db_index=True)),
                        (
                            "history_change_reason",
                            models.CharField(max_length=100, null=True),
                        ),
                        (
                            "history_type",
                            models.CharField(
                                choices=[
                                    ("+", "Created"),
                                    ("~", "Changed"),
                                    ("-", "Deleted"),
                                ],
                                max_length=1,
                            ),
                        ),
                        (
                            "history_user",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "reservation",
                            models.ForeignKey(
                                blank=True,
                                db_constraint=False,
                                null=True,
                                on_delete=django.db.models.deletion.DO_NOTHING,
                                related_name="+",
                                to="reservation.reservation",
                                verbose_name="Réservation",
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                blank=True,
                                db_constraint=False,
                                null=True,
                                on_delete=django.db.models.deletion.DO_NOTHING,
                                related_name="+",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Utilisateur",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Historique Notification",
                        "verbose_name_plural": "Historiques Notifications",
                        "ordering": ("-history_date", "-history_id"),
                        "get_latest_by": ("history_date", "history_id"),
                    },
                    bases=(simple_history.models.HistoricalChanges, models.Model),
                ),
                migrations.CreateModel(
                    name="HistoricalNotificationPreference",
                    fields=[
                        (
                            "id",
                            models.BigIntegerField(
                                auto_created=True,
                                blank=True,
                                db_index=True,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "notify_check_in",
                            models.BooleanField(
                                default=True, verbose_name="Notifier à l'arrivée"
                            ),
                        ),
                        (
                            "notify_check_out",
                            models.BooleanField(
                                default=True, verbose_name="Notifier au départ"
                            ),
                        ),
                        (
                            "reminder_minutes",
                            models.IntegerField(
                                choices=[
                                    (0, "Au moment de l'événement"),
                                    (15, "15 minutes avant"),
                                    (30, "30 minutes avant"),
                                    (60, "1 heure avant"),
                                    (120, "2 heures avant"),
                                    (1440, "1 jour avant"),
                                    (2880, "2 jours avant"),
                                ],
                                default=60,
                                verbose_name="Rappel avant (minutes)",
                            ),
                        ),
                        (
                            "date_created",
                            models.DateTimeField(
                                blank=True, editable=False, verbose_name="Date création"
                            ),
                        ),
                        (
                            "date_updated",
                            models.DateTimeField(
                                blank=True,
                                editable=False,
                                verbose_name="Date modification",
                            ),
                        ),
                        (
                            "history_id",
                            models.AutoField(primary_key=True, serialize=False),
                        ),
                        ("history_date", models.DateTimeField(db_index=True)),
                        (
                            "history_change_reason",
                            models.CharField(max_length=100, null=True),
                        ),
                        (
                            "history_type",
                            models.CharField(
                                choices=[
                                    ("+", "Created"),
                                    ("~", "Changed"),
                                    ("-", "Deleted"),
                                ],
                                max_length=1,
                            ),
                        ),
                        (
                            "history_user",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                blank=True,
                                db_constraint=False,
                                null=True,
                                on_delete=django.db.models.deletion.DO_NOTHING,
                                related_name="+",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Utilisateur",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Historique Préférence Notification",
                        "verbose_name_plural": "Historiques Préférences Notifications",
                        "ordering": ("-history_date", "-history_id"),
                        "get_latest_by": ("history_date", "history_id"),
                    },
                    bases=(simple_history.models.HistoricalChanges, models.Model),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "reservation_historicalnotification" RENAME TO "notification_historicalnotification"',
                    reverse_sql='ALTER TABLE "notification_historicalnotification" RENAME TO "reservation_historicalnotification"',
                ),
                migrations.RunSQL(
                    sql='ALTER TABLE "reservation_historicalnotificationpreference" RENAME TO "notification_historicalnotificationpreference"',
                    reverse_sql='ALTER TABLE "notification_historicalnotificationpreference" RENAME TO "reservation_historicalnotificationpreference"',
                ),
            ],
        ),
    ]
