# Generated by Django 6.1.1 on 2026-10-10 14:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InferenceLease",
            fields=[
                (
                    "name",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("owner", models.UUIDField(null=True)),
                ("expires_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="KnowledgeDocument",
            fields=[
                (
                    "document_id",
                    models.CharField(max_length=80, primary_key=True, serialize=False),
                ),
                (
                    "application_id",
                    models.CharField(default="reservation", max_length=32),
                ),
                ("document_version", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("localized_content", models.JSONField(blank=True, default=dict)),
                ("keywords", models.JSONField(default=list)),
                ("category", models.CharField(max_length=40)),
                ("sensitivity", models.CharField(default="member", max_length=20)),
                ("required_capabilities", models.JSONField(default=list)),
                ("tenant_scope_id", models.PositiveIntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instruction_id", models.UUIDField(db_index=True, null=True)),
                ("actor_id", models.PositiveBigIntegerField(null=True)),
                ("actor_label", models.CharField(blank=True, max_length=254)),
                ("resource", models.CharField(blank=True, max_length=32)),
                ("record_id", models.PositiveBigIntegerField(null=True)),
                ("changed_fields", models.JSONField(default=list)),
                (
                    "source",
                    models.CharField(default="chat_ai_assistant", max_length=32),
                ),
                ("scope_id", models.PositiveBigIntegerField(null=True)),
                ("application", models.CharField(default="reservation", max_length=32)),
                ("tool", models.CharField(max_length=64)),
                ("outcome", models.CharField(max_length=40)),
                ("correlation_id", models.UUIDField()),
                ("model_version", models.CharField(max_length=120)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scope_id", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "application",
                    models.CharField(
                        default="reservation", editable=False, max_length=32
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
                ("references", models.JSONField(default=dict)),
                ("authorization_stamp", models.CharField(max_length=64)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "user"), ("assistant", "assistant")],
                        max_length=12,
                    ),
                ),
                ("text", models.TextField(blank=True)),
                ("action", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("request_id", models.UUIDField(default=uuid.uuid4)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat_ai.conversation",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("helpful", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat_ai.message",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PendingAction",
            fields=[
                ("instruction_id", models.UUIDField(null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scope_id", models.PositiveIntegerField(default=1, editable=False)),
                ("resource", models.CharField(max_length=20)),
                ("record_id", models.PositiveBigIntegerField()),
                ("operation", models.CharField(max_length=12)),
                ("changes", models.JSONField(default=dict)),
                ("fingerprint", models.CharField(max_length=64)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["user", "scope_id", "-updated_at"],
                name="chat_ai_con_user_id_c8549f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.UniqueConstraint(
                fields=("conversation", "request_id", "role"),
                name="chat_ai_unique_request_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="feedback",
            constraint=models.UniqueConstraint(
                fields=("message", "user"), name="chat_ai_unique_feedback"
            ),
        ),
    ]
