# Generated by Django 6.0.3 on 2026-03-30 12:00

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalLocal",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "nom",
                    models.CharField(db_index=True, max_length=200, verbose_name="Nom"),
                ),
                (
                    "type_local",
                    models.CharField(
                        choices=[("Bureau", "Bureau"), ("Magasin", "Magasin")],
                        max_length=50,
                        verbose_name="Type de local",
                    ),
                ),
                (
                    "adresse",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="Adresse"
                    ),
                ),
                (
                    "superficie",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Superficie (m²)",
                    ),
                ),
                (
                    "prix_achat",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Prix d'achat"
                    ),
                ),
                (
                    "prix_location_mensuel",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Prix de location mensuel HT",
                    ),
                ),
                (
                    "en_location",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="En location"
                    ),
                ),
                (
                    "locataire_nom",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Nom du locataire",
                    ),
                ),
                (
                    "date_debut_location",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de début de location"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "date_created",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("date_updated", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Local",
                "verbose_name_plural": "historical Locaux",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Local",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=200, unique=True, verbose_name="Nom"),
                ),
                (
                    "type_local",
                    models.CharField(
                        choices=[("Bureau", "Bureau"), ("Magasin", "Magasin")],
                        max_length=50,
                        verbose_name="Type de local",
                    ),
                ),
                (
                    "adresse",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="Adresse"
                    ),
                ),
                (
                    "superficie",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Superficie (m²)",
                    ),
                ),
                (
                    "prix_achat",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Prix d'achat"
                    ),
                ),
                (
                    "prix_location_mensuel",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Prix de location mensuel HT",
                    ),
                ),
                (
                    "en_location",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="En location"
                    ),
                ),
                (
                    "locataire_nom",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Nom du locataire",
                    ),
                ),
                (
                    "date_debut_location",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de début de location"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locaux",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Local",
                "verbose_name_plural": "Locaux",
                "ordering": ("nom",),
            },
        ),
        migrations.CreateModel(
            name="Loyer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mois", models.IntegerField(db_index=True, verbose_name="Mois")),
                ("annee", models.IntegerField(db_index=True, verbose_name="Année")),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant"
                    ),
                ),
                (
                    "paye",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Payé"
                    ),
                ),
                (
                    "date_paiement",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de paiement"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loyers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loyers",
                        to="local.local",
                        verbose_name="Local",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loyer",
                "verbose_name_plural": "Loyers",
                "ordering": ("-annee", "-mois"),
                "indexes": [
                    models.Index(
                        fields=["local", "annee", "mois"],
                        name="local_loyer_local_i_4ed7a8_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("local", "mois", "annee"),
                        name="unique_loyer_per_local_month_year",
                    )
                ],
            },
        ),
    ]
