# Generated by Django 6.0.3 on 2026-03-31 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0001_initial"),
        ("local", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallocal",
            name="building",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="building.building",
                verbose_name="Résidence",
            ),
        ),
        migrations.AddField(
            model_name="local",
            name="building",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="locaux",
                to="building.building",
                verbose_name="Résidence",
            ),
        ),
    ]
