# Generated by Django 6.0.4 on 2026-04-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("local", "0003_historicalloyer"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalTypeOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Type de local"
                    ),
                ),
            ],
            options={
                "verbose_name": "Type de local",
                "verbose_name_plural": "Types de local",
                "ordering": ("nom",),
            },
        ),
    ]
