# Generated by Django 6.0.3 on 2026-03-26 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ws", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wsmaintenancestate",
            options={
                "verbose_name": "Maintenance",
                "verbose_name_plural": "Maintenance",
            },
        ),
    ]
