# Generated by Django 6.1.1 on 2026-10-09 12:43

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ws", "0002_alter_wsmaintenancestate_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangelogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.localdate, unique=True
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Release version. Leave empty for older, unversioned entries.",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^(0|[1-9]\\d{0,5})\\.(0|[1-9]\\d{0,5})\\.(0|[1-9]\\d{0,5})\\Z",
                                "Use a release version such as 1.2.0 (three numbers, up to six digits each).",
                            )
                        ],
                    ),
                ),
                (
                    "title_fr",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Title — French"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Title — English"
                    ),
                ),
                (
                    "changes_fr",
                    models.TextField(
                        blank=True,
                        help_text="One change per line. Plain language, no HTML.",
                        verbose_name="Changes — French",
                    ),
                ),
                (
                    "changes_en",
                    models.TextField(
                        blank=True,
                        help_text="One change per line. Plain language, no HTML.",
                        verbose_name="Changes — English",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Published"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Changelog entry",
                "verbose_name_plural": "Changelog",
                "ordering": ("-date", "-pk"),
            },
        ),
        migrations.AddField(
            model_name="wsmaintenancestate",
            name="version",
            field=models.CharField(
                default="0.1.0",
                help_text="Publish only after this frontend version is deployed and healthy.",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(0|[1-9]\\d{0,5})\\.(0|[1-9]\\d{0,5})\\.(0|[1-9]\\d{0,5})\\Z",
                        "Use a release version such as 1.2.0 (three numbers, up to six digits each).",
                    )
                ],
                verbose_name="Version",
            ),
        ),
    ]
