# Generated by Django 6.0.3 on 2026-03-10 13:45

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Apartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Identifiant court de l'appartement (ex: 5B)",
                        max_length=20,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nom complet de l'appartement",
                        max_length=100,
                        verbose_name="Nom",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Actif"
                    ),
                ),
            ],
            options={
                "verbose_name": "Appartement",
                "verbose_name_plural": "Appartements",
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="HistoricalReservation",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "guest_name",
                    models.CharField(
                        help_text="Nom complet du client",
                        max_length=200,
                        verbose_name="Nom du client",
                    ),
                ),
                (
                    "check_in",
                    models.DateField(db_index=True, verbose_name="Date d'arrivée"),
                ),
                (
                    "check_out",
                    models.DateField(db_index=True, verbose_name="Date de départ"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant total de la réservation en MAD",
                        max_digits=12,
                        verbose_name="Montant (MAD)",
                    ),
                ),
                (
                    "payment_source",
                    models.CharField(
                        choices=[
                            ("Booking", "Booking.com"),
                            ("Airbnb", "Airbnb"),
                            ("Cash", "Espèces"),
                            ("Bank", "Virement bancaire"),
                        ],
                        db_index=True,
                        default="Cash",
                        max_length=20,
                        verbose_name="Source de paiement",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        verbose_name="Date création",
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Date modification"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "apartment",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="reservation.apartment",
                        verbose_name="Appartement",
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique Réservation",
                "verbose_name_plural": "Historiques Réservations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guest_name",
                    models.CharField(
                        help_text="Nom complet du client",
                        max_length=200,
                        verbose_name="Nom du client",
                    ),
                ),
                (
                    "check_in",
                    models.DateField(db_index=True, verbose_name="Date d'arrivée"),
                ),
                (
                    "check_out",
                    models.DateField(db_index=True, verbose_name="Date de départ"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant total de la réservation en MAD",
                        max_digits=12,
                        verbose_name="Montant (MAD)",
                    ),
                ),
                (
                    "payment_source",
                    models.CharField(
                        choices=[
                            ("Booking", "Booking.com"),
                            ("Airbnb", "Airbnb"),
                            ("Cash", "Espèces"),
                            ("Bank", "Virement bancaire"),
                        ],
                        db_index=True,
                        default="Cash",
                        max_length=20,
                        verbose_name="Source de paiement",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Date création"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date modification"
                    ),
                ),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="reservation.apartment",
                        verbose_name="Appartement",
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réservation",
                "verbose_name_plural": "Réservations",
                "ordering": ("-check_in",),
                "indexes": [
                    models.Index(
                        fields=["apartment", "check_in"],
                        name="reservation_apartme_64f7f7_idx",
                    ),
                    models.Index(
                        fields=["check_in", "check_out"],
                        name="reservation_check_i_925118_idx",
                    ),
                    models.Index(
                        fields=["payment_source"], name="reservation_payment_232745_idx"
                    ),
                ],
            },
        ),
    ]
