# Generated by Django 6.0.3 on 2026-03-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalreservation",
            name="payment_source",
            field=models.CharField(
                db_index=True,
                default="Cash",
                max_length=50,
                verbose_name="Source de paiement",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="payment_source",
            field=models.CharField(
                db_index=True,
                default="Cash",
                max_length=50,
                verbose_name="Source de paiement",
            ),
        ),
    ]
