# Generated by Django 6.0.3 on 2026-03-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0002_alter_historicalreservation_payment_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="monthly_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Coût mensuel de location de l'appartement (MAD)",
                max_digits=12,
                verbose_name="Coût mensuel",
            ),
        ),
    ]
