# Generated by Django 6.0.3 on 2026-03-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0003_add_apartment_monthly_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreservation",
            name="amount_returned",
            field=models.BooleanField(
                default=False,
                help_text="Indique si le montant a été retourné",
                verbose_name="Montant retourné",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="amount_returned",
            field=models.BooleanField(
                default=False,
                help_text="Indique si le montant a été retourné",
                verbose_name="Montant retourné",
            ),
        ),
    ]
