# Generated by Django 6.0.3 on 2026-03-26 08:33

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0005_simplify_apartment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalCost",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "cost_type",
                    models.CharField(
                        choices=[
                            ("Maintenance", "Maintenance"),
                            ("Utilities", "Charges"),
                            ("Tax", "Impôts"),
                            ("Other", "Autre"),
                        ],
                        db_index=True,
                        default="Other",
                        max_length=50,
                        verbose_name="Type de coût",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant du coût en MAD",
                        max_digits=12,
                        verbose_name="Montant (MAD)",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="Date du coût")),
                ("month", models.IntegerField(db_index=True, verbose_name="Mois")),
                ("year", models.IntegerField(db_index=True, verbose_name="Année")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        verbose_name="Date création",
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Date modification"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "apartment",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="reservation.apartment",
                        verbose_name="Appartement",
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique Coût",
                "verbose_name_plural": "Historiques Coûts",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Cost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cost_type",
                    models.CharField(
                        choices=[
                            ("Maintenance", "Maintenance"),
                            ("Utilities", "Charges"),
                            ("Tax", "Impôts"),
                            ("Other", "Autre"),
                        ],
                        db_index=True,
                        default="Other",
                        max_length=50,
                        verbose_name="Type de coût",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant du coût en MAD",
                        max_digits=12,
                        verbose_name="Montant (MAD)",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="Date du coût")),
                ("month", models.IntegerField(db_index=True, verbose_name="Mois")),
                ("year", models.IntegerField(db_index=True, verbose_name="Année")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Date création"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date modification"
                    ),
                ),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costs",
                        to="reservation.apartment",
                        verbose_name="Appartement",
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="costs_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coût",
                "verbose_name_plural": "Coûts",
                "ordering": ("-date",),
                "indexes": [
                    models.Index(
                        fields=["apartment", "year", "month"],
                        name="reservation_apartme_20eda4_idx",
                    ),
                    models.Index(
                        fields=["year", "month"], name="reservation_year_6f071f_idx"
                    ),
                    models.Index(
                        fields=["cost_type"], name="reservation_cost_ty_cb6ba0_idx"
                    ),
                ],
            },
        ),
    ]
