# Generated by Django 6.0.3 on 2026-03-26 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0006_historicalcost_cost"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="cost",
            name="reservation_apartme_20eda4_idx",
        ),
        migrations.RemoveIndex(
            model_name="cost",
            name="reservation_year_6f071f_idx",
        ),
        migrations.RemoveIndex(
            model_name="cost",
            name="reservation_cost_ty_cb6ba0_idx",
        ),
        migrations.RemoveField(
            model_name="cost",
            name="apartment",
        ),
        migrations.RemoveField(
            model_name="cost",
            name="created_by_user",
        ),
        migrations.DeleteModel(
            name="HistoricalCost",
        ),
        migrations.DeleteModel(
            name="Cost",
        ),
    ]
