# Generated by Django 6.0.3 on 2026-03-26 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0007_remove_cost_reservation_apartme_20eda4_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Description du coût",
                        max_length=300,
                        verbose_name="Description",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant (MAD)"
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="Date")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Entretien", "Entretien"),
                            ("Charges", "Charges"),
                            ("Assurance", "Assurance"),
                            ("Taxes", "Taxes"),
                            ("Autre", "Autre"),
                        ],
                        db_index=True,
                        default="Autre",
                        max_length=50,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date création"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date modification"
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="costs_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coût",
                "verbose_name_plural": "Coûts",
                "ordering": ("-date",),
            },
        ),
    ]
