# Generated by Django 6.0.3 on 2026-03-31 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0001_initial"),
        ("reservation", "0009_notification_notificationpreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="building",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="apartments",
                to="building.building",
                verbose_name="Résidence",
            ),
        ),
    ]
