# Generated by Django 6.0.4 on 2026-04-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0012_remove_notification_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="CostCategoryOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Catégorie de coût"
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie de coût",
                "verbose_name_plural": "Catégories de coût",
                "ordering": ("nom",),
            },
        ),
        migrations.CreateModel(
            name="PaymentSourceOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Source de paiement"
                    ),
                ),
            ],
            options={
                "verbose_name": "Source de paiement",
                "verbose_name_plural": "Sources de paiement",
                "ordering": ("nom",),
            },
        ),
    ]
