# Generated by Django 6.0.3 on 2026-04-17 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0001_initial"),
        ("reservation", "0013_costcategoryoption_paymentsourceoption"),
    ]

    operations = [
        migrations.AddField(
            model_name="cost",
            name="building",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="costs",
                to="building.building",
                verbose_name="Résidence",
            ),
        ),
        migrations.AddField(
            model_name="historicalcost",
            name="building",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="building.building",
                verbose_name="Résidence",
            ),
        ),
    ]