# Generated by Django 6.0.3 on 2026-05-05 12:10

from decimal import Decimal

from django.db import migrations, models


PAYMENT_SOURCE_TOTAL_FIELDS = {
    "Booking": "booking_total",
    "Airbnb": "airbnb_total",
    "Cash": "cash_revenue_total",
    "Bank": "bank_total",
}
PAYMENT_SOURCE_ALIASES = {
    "booking": "Booking",
    "booking.com": "Booking",
    "airbnb": "Airbnb",
    "cash": "Cash",
    "espèces": "Cash",
    "especes": "Cash",
    "espèce": "Cash",
    "espece": "Cash",
    "bank": "Bank",
    "bank transfer": "Bank",
    "virement": "Bank",
    "virement bancaire": "Bank",
}


def normalize_payment_source(payment_source):
    if not payment_source:
        return None
    return PAYMENT_SOURCE_ALIASES.get(payment_source.strip().casefold())


def backfill_hilton_report_source_totals(apps, schema_editor):
    Building = apps.get_model("building", "Building")
    Reservation = apps.get_model("reservation", "Reservation")
    HiltonReport = apps.get_model("reservation", "HiltonReport")
    HiltonReportManualLine = apps.get_model("reservation", "HiltonReportManualLine")

    building = Building.objects.filter(nom__iexact="Hilton residence").first()
    if not building:
        return

    for report in HiltonReport.objects.all():
        totals = {
            "booking_total": Decimal("0.00"),
            "airbnb_total": Decimal("0.00"),
            "cash_revenue_total": Decimal("0.00"),
            "bank_total": Decimal("0.00"),
        }
        reservations = Reservation.objects.filter(
            apartment__building=building,
            check_in__gte=report.start_date,
            check_in__lt=report.end_date,
        ).values("payment_source", "amount")
        for reservation in reservations:
            source = normalize_payment_source(reservation["payment_source"])
            if source:
                totals[PAYMENT_SOURCE_TOTAL_FIELDS[source]] += (
                    reservation["amount"] or Decimal("0.00")
                )

        manual_cost_total = (
            HiltonReportManualLine.objects.filter(
                report=report,
                line_type="cost",
            ).aggregate(total=models.Sum("amount"))["total"]
            or Decimal("0.00")
        )
        report.booking_total = totals["booking_total"]
        report.airbnb_total = totals["airbnb_total"]
        report.cash_revenue_total = totals["cash_revenue_total"]
        report.cash_total = totals["cash_revenue_total"] - manual_cost_total
        report.bank_total = totals["bank_total"]
        report.save(
            update_fields=[
                "booking_total",
                "airbnb_total",
                "cash_revenue_total",
                "cash_total",
                "bank_total",
                "date_updated",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0001_initial"),
        ("reservation", "0015_hilton_reports"),
    ]

    operations = [
        migrations.AddField(
            model_name="hiltonreport",
            name="airbnb_total",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Total Airbnb"
            ),
        ),
        migrations.AddField(
            model_name="hiltonreport",
            name="bank_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Total virement bancaire",
            ),
        ),
        migrations.AddField(
            model_name="hiltonreport",
            name="booking_total",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Total Booking"
            ),
        ),
        migrations.AddField(
            model_name="hiltonreport",
            name="cash_revenue_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Total espèces avant coûts",
            ),
        ),
        migrations.AddField(
            model_name="hiltonreport",
            name="cash_total",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Total espèces"
            ),
        ),
        migrations.RunPython(
            backfill_hilton_report_source_totals,
            migrations.RunPython.noop,
        ),
    ]
