# Generated by Django 6.1.1 on 2026-09-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0019_assign_legacy_apartment_buildings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cost",
            name="category",
            field=models.CharField(
                db_index=True,
                default="Autre",
                max_length=100,
                verbose_name="Catégorie",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcost",
            name="category",
            field=models.CharField(
                db_index=True,
                default="Autre",
                max_length=100,
                verbose_name="Catégorie",
            ),
        ),
    ]
